# Generated by Django 6.0 on 2025-12-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('fast_food', 'Fast Food'), ('national', 'National'), ('drinks', 'Drinks')], max_length=20),
        ),
    ]
