# Generated by Django 6.0 on 2025-12-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0002_orderitem_price_alter_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
